spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.55.111:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=PRC
    username: work
    password: 123456
